title : 'IM Server'

user : 'example@gmail.com'
pass : 'your-gmail-passwd'
server : 'talk.google.com'
port : 5222

to : 
   - 'foo@gmail.com'
   - 'bar@jabber.jp'

     
feed_max_size : 40

# mongo db config
mongo_server : '127.0.0.1'
mongo_port : 27017
mongo_dbname : 'im-server'
     
